function createfigure(XData1, XData2, YData1, XData3, YData2, XData4, YData3, XData5, YData4, XData6, YData5, XData7, YData6, XData8, YData7, XData9, YData8, XData10, YData9, XData11, YData10, XData12, YData11, XData13, YData12, XData14, YData13)
%CREATEFIGURE(XDATA1, XDATA2, YDATA1, XDATA3, YDATA2, XDATA4, YDATA3, XDATA5, YDATA4, XDATA6, YDATA5, XDATA7, YDATA6, XDATA8, YDATA7, XDATA9, YDATA8, XDATA10, YDATA9, XDATA11, YDATA10, XDATA12, YDATA11, XDATA13, YDATA12, XDATA14, YDATA13)
%  XDATA1:  line xdata
%  XDATA2:  line xdata
%  YDATA1:  line ydata
%  XDATA3:  line xdata
%  YDATA2:  line ydata
%  XDATA4:  line xdata
%  YDATA3:  line ydata
%  XDATA5:  line xdata
%  YDATA4:  line ydata
%  XDATA6:  line xdata
%  YDATA5:  line ydata
%  XDATA7:  line xdata
%  YDATA6:  line ydata
%  XDATA8:  line xdata
%  YDATA7:  line ydata
%  XDATA9:  line xdata
%  YDATA8:  line ydata
%  XDATA10:  line xdata
%  YDATA9:  line ydata
%  XDATA11:  line xdata
%  YDATA10:  line ydata
%  XDATA12:  line xdata
%  YDATA11:  line ydata
%  XDATA13:  line xdata
%  YDATA12:  line ydata
%  XDATA14:  line xdata
%  YDATA13:  line ydata

%  Generated by JOHNMATLAB on 26-Nov-2016 20:25:13

% Create figure
figure1 = figure('Tag','TRAINING_PLOTROC','NumberTitle','off',...
    'Name','Neural Network Training Receiver Operating Characteristic (plotroc), Epoch 73, Validation stop.');

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create line
line(XData1,XData1,'Parent',subplot1,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData2,YData1,'Parent',subplot1,'DisplayName','Class 1','LineWidth',2,...
    'Color',[0 0 1]);

% Create line
line(XData1,XData1,'Parent',subplot1,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData2,YData1,'Parent',subplot1,'DisplayName','Class 2','LineWidth',2,...
    'Color',[0 0.5 0.5]);

% Create line
line(XData1,XData1,'Parent',subplot1,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData2,YData1,'Parent',subplot1,'DisplayName','Class 3','LineWidth',2,...
    'Color',[0 1 0]);

% Create line
line(XData1,XData1,'Parent',subplot1,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData3,YData2,'Parent',subplot1,'DisplayName','Class 4','LineWidth',2,...
    'Color',[0.5 0.5 0]);

% Create line
line(XData1,XData1,'Parent',subplot1,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData4,YData3,'Parent',subplot1,'DisplayName','Class 5','LineWidth',2,...
    'Color',[1 0 0]);

% Create line
line(XData1,XData1,'Parent',subplot1,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData3,YData2,'Parent',subplot1,'DisplayName','Class 6','LineWidth',2,...
    'Color',[0.5 0 0.5]);

% Create xlabel
xlabel('False Positive Rate');

% Create title
title('Training ROC');

% Create ylabel
ylabel('True Positive Rate');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 1]);
% Set the remaining axes properties
set(subplot1,'DataAspectRatio',[1 1 1]);
% Create legend
legend(subplot1,'show');

% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create line
line(XData1,XData1,'Parent',subplot2,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData5,YData4,'Parent',subplot2,'LineWidth',2,'Color',[0 0 1]);

% Create line
line(XData1,XData1,'Parent',subplot2,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData6,YData5,'Parent',subplot2,'LineWidth',2,'Color',[0 0.5 0.5]);

% Create line
line(XData1,XData1,'Parent',subplot2,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData5,YData4,'Parent',subplot2,'LineWidth',2,'Color',[0 1 0]);

% Create line
line(XData1,XData1,'Parent',subplot2,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData7,YData6,'Parent',subplot2,'LineWidth',2,'Color',[0.5 0.5 0]);

% Create line
line(XData1,XData1,'Parent',subplot2,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData8,YData7,'Parent',subplot2,'LineWidth',2,'Color',[1 0 0]);

% Create line
line(XData1,XData1,'Parent',subplot2,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData9,YData8,'Parent',subplot2,'LineWidth',2,'Color',[0.5 0 0.5]);

% Create xlabel
xlabel('False Positive Rate');

% Create title
title('Validation ROC');

% Create ylabel
ylabel('True Positive Rate');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0 1]);
% Set the remaining axes properties
set(subplot2,'DataAspectRatio',[1 1 1]);
% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create line
line(XData1,XData1,'Parent',subplot3,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData5,YData4,'Parent',subplot3,'LineWidth',2,'Color',[0 0 1]);

% Create line
line(XData1,XData1,'Parent',subplot3,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData5,YData4,'Parent',subplot3,'LineWidth',2,'Color',[0 0.5 0.5]);

% Create line
line(XData1,XData1,'Parent',subplot3,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData5,YData4,'Parent',subplot3,'LineWidth',2,'Color',[0 1 0]);

% Create line
line(XData1,XData1,'Parent',subplot3,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData5,YData4,'Parent',subplot3,'LineWidth',2,'Color',[0.5 0.5 0]);

% Create line
line(XData1,XData1,'Parent',subplot3,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData5,YData4,'Parent',subplot3,'LineWidth',2,'Color',[1 0 0]);

% Create line
line(XData1,XData1,'Parent',subplot3,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData5,YData4,'Parent',subplot3,'LineWidth',2,'Color',[0.5 0 0.5]);

% Create xlabel
xlabel('False Positive Rate');

% Create title
title('Test ROC');

% Create ylabel
ylabel('True Positive Rate');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[0 1]);
% Set the remaining axes properties
set(subplot3,'DataAspectRatio',[1 1 1]);
% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
hold(subplot4,'on');

% Create line
line(XData1,XData1,'Parent',subplot4,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData10,YData9,'Parent',subplot4,'LineWidth',2,'Color',[0 0 1]);

% Create line
line(XData1,XData1,'Parent',subplot4,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData11,YData10,'Parent',subplot4,'LineWidth',2,'Color',[0 0.5 0.5]);

% Create line
line(XData1,XData1,'Parent',subplot4,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData10,YData9,'Parent',subplot4,'LineWidth',2,'Color',[0 1 0]);

% Create line
line(XData1,XData1,'Parent',subplot4,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData12,YData11,'Parent',subplot4,'LineWidth',2,'Color',[0.5 0.5 0]);

% Create line
line(XData1,XData1,'Parent',subplot4,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData13,YData12,'Parent',subplot4,'LineWidth',2,'Color',[1 0 0]);

% Create line
line(XData1,XData1,'Parent',subplot4,'LineWidth',2,'Color',[0.8 0.8 0.8]);

% Create line
line(XData14,YData13,'Parent',subplot4,'LineWidth',2,'Color',[0.5 0 0.5]);

% Create xlabel
xlabel('False Positive Rate');

% Create title
title('All ROC');

% Create ylabel
ylabel('True Positive Rate');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[0 1]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[0 1]);
% Set the remaining axes properties
set(subplot4,'DataAspectRatio',[1 1 1]);
% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information
% uicontrol(...);

