function horizontal6code(xdata1, ydata1)
%CREATEFIGURE(XDATA1, YDATA1)
%  XDATA1:  histogram2 x data
%  YDATA1:  histogram2 y data

%  Generated by JOHNMATLAB on 19-Jan-2016 11:27:23

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);

% Create histogram2
histogram2(xdata1,ydata1,'Parent',axes1,'BinMethod','auto');

view(axes1,[-37.5 30]);
box(axes1,'on');
grid(axes1,'on');
axis(axes1,'tight');
