function createfigure(X1, YMatrix1, X2)
%CREATEFIGURE(X1, YMATRIX1, X2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data

%  Generated by JOHNMATLAB on 29-Oct-2016 12:15:56

% Create figure
figure1 = figure('Tag','PLOTREGRESSION1','NumberTitle','off',...
    'Name','Regression (plotregression)');

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1);
set(plot1(1),'DisplayName','Y = T','LineStyle',':','Color',[0 0 0]);
set(plot1(2),'DisplayName','Fit','LineWidth',2,'Color',[0 0 1]);

% Create plot
plot(X2,X2,'Parent',subplot1,'DisplayName','Data','Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);

% Create xlabel
xlabel('Target','FontWeight','bold','FontSize',12);

% Create title
title('Training: R=1','FontWeight','bold','FontSize',12);

% Create ylabel
ylabel('Output ~= 1*Target + -4.2e-14','FontWeight','bold','FontSize',12);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[-913.5 0]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-913.5 0]);
box(subplot1,'on');
axis(subplot1,'square');
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'Location','northwest');

% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X1,YMatrix1,'Parent',subplot2);
set(plot2(1),'DisplayName','Y = T','LineStyle',':','Color',[0 0 0]);
set(plot2(2),'DisplayName','Fit','LineWidth',2,'Color',[0 1 0]);

% Create plot
plot(X2,X2,'Parent',subplot2,'DisplayName','Data','Marker','o',...
    'LineStyle','none',...
    'Color',[0 0 0]);

% Create xlabel
xlabel('Target','FontWeight','bold','FontSize',12);

% Create title
title('All: R=1','FontWeight','bold','FontSize',12);

% Create ylabel
ylabel('Output ~= 1*Target + -4.2e-14','FontWeight','bold','FontSize',12);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[-913.5 0]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-913.5 0]);
box(subplot2,'on');
axis(subplot2,'square');
% Create legend
legend2 = legend(subplot2,'show');
set(legend2,'Location','northwest');

% uicontrol currently does not support code generation, enter 'doc uicontrol' for correct input syntax
% In order to generate code for uicontrol, you may use GUIDE. Enter 'doc guide' for more information
% uicontrol(...);

