%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\User\Desktop\vertical-5.xls
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Generated by JOHNMATLAB on 2015/11/29 17:43:12

%% Import the data
[~, ~, raw] = xlsread('C:\Users\User\Desktop\vertical-5.xls','Sheet1','A2:B437');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
vertical5 = table;

%% Allocate imported array to column variable names
vertical5.X = data(:,1);
vertical5.Z = data(:,2);

%% Clear temporary variables
clearvars data raw R;