%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\User\Desktop\vertical-2.xls
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Generated by JOHNMATLAB on 2015/11/28 21:00:38

%% Import the data
[~, ~, raw] = xlsread('C:\Users\User\Desktop\vertical-2.xls','Sheet1','A2:B460');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
X = data(:,1);
Z = data(:,2);

%% Clear temporary variables
clearvars data raw R;